/*
 * This source file was generated by the Gradle 'init' task
 */
package org.dlt;

public class App {
    public static String filePath = null;

    public static void main(String[] args) {
        if (args.length > 0) {
            filePath = args[0];
        }

        TOI toi = new TOI();
        toi.init(filePath).format();
    }
}
